"use strict";

module.exports = {
  returnTypes: {
    ActionExpression: "ast.Expression",
    AnyMatcher: "ast.Expression",
    BareCodeBlock: "ast.Code",
    Boundary: "ast.Boundary",
    Boundaries: "ast.Boundaries",
    CharacterClassMatcher: "ast.Expression",
    ChoiceExpression: "ast.Expression",
    CloseCurly: "ast.Punctuation",
    Constant: "ast.BoundaryConstant",
    Dquote: "ast.Punctuation",
    Equals: "ast.Punctuation",
    Expression: "ast.Expression",
    Grammar: "ast.Grammar",
    IdentifierName: "ast.Expression",
    Initializer: "ast.Initializer",
    LabeledExpression: "ast.Expression",
    LiteralMatcher: "ast.Expression",
    OpenCurly: "ast.Punctuation",
    PrefixedExpression: "ast.Expression",
    PrimaryExpression: "ast.Expression",
    Program: "ast.Program",
    RepeatedExpression: "ast.RepeatedExpression",
    Rule: "ast.Rule",
    RuleReferenceExpression: "ast.Expression",
    SemanticPredicateExpression: "ast.Expression",
    SequenceExpression: "ast.Expression",
    Slash: "ast.Punctuation",
    Squote: "ast.Punctuation",
    SuffixedExpression: "ast.Expression",
    TopLevelInitializer: "ast.TopLevelInitializer",
  }
};
